// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Railway.Models.Database;

namespace Railway.Migrations
{
    [DbContext(typeof(IteaDbContext))]
    [Migration("20200429195758_AllChanges")]
    partial class AllChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Railway.Models.Entities.Carriage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<int?>("TrainId");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("Carriages");
                });

            modelBuilder.Entity("Railway.Models.Entities.CarriageService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarriageId");

                    b.Property<DateTime?>("Created");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CarriageId");

                    b.ToTable("CarriageServices");
                });

            modelBuilder.Entity("Railway.Models.Entities.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("IPAddress");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<DateTime>("LoginTime");

                    b.Property<string>("UserDevice");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Railway.Models.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName");

                    b.Property<DateTime?>("Created");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<string>("StationName");

                    b.Property<int>("StationType");

                    b.Property<int?>("TrainId");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Railway.Models.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarriageId");

                    b.Property<DateTime?>("Created");

                    b.Property<int?>("FinishStationId");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<int>("PlaceNumber");

                    b.Property<decimal>("Price");

                    b.Property<int?>("StartStationId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CarriageId");

                    b.HasIndex("FinishStationId");

                    b.HasIndex("StartStationId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Railway.Models.Entities.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<int>("TrainNumber");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Railway.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Email");

                    b.Property<DateTime?>("LastUpdated");

                    b.Property<string>("Password");

                    b.Property<string>("RealName");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Railway.Models.Entities.Carriage", b =>
                {
                    b.HasOne("Railway.Models.Entities.Train")
                        .WithMany("Carriages")
                        .HasForeignKey("TrainId");
                });

            modelBuilder.Entity("Railway.Models.Entities.CarriageService", b =>
                {
                    b.HasOne("Railway.Models.Entities.Carriage", "Carriage")
                        .WithMany()
                        .HasForeignKey("CarriageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Railway.Models.Entities.LoginHistory", b =>
                {
                    b.HasOne("Railway.Models.Entities.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Railway.Models.Entities.Station", b =>
                {
                    b.HasOne("Railway.Models.Entities.Train")
                        .WithMany("Stations")
                        .HasForeignKey("TrainId");
                });

            modelBuilder.Entity("Railway.Models.Entities.Ticket", b =>
                {
                    b.HasOne("Railway.Models.Entities.Carriage", "Carriage")
                        .WithMany()
                        .HasForeignKey("CarriageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Railway.Models.Entities.Station", "FinishStation")
                        .WithMany()
                        .HasForeignKey("FinishStationId");

                    b.HasOne("Railway.Models.Entities.Station", "StartStation")
                        .WithMany()
                        .HasForeignKey("StartStationId");

                    b.HasOne("Railway.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
